apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: nginx:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
          env:
            - name: MSG
              value: "Hello from app1."
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html

      volumes:
        - name: html-volume
          configMap:
            name: app-one-html

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-one-html
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif; text-align: center; margin-top: 40px;">
        <h1>Hello from app one!</h1>
      </body>
    </html>

---

apiVersion: v1
kind: Service
metadata:
  name: app-one-service
spec:
  selector:
    app: app-one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80