Vagrant.configure("2") do |config|

    config.vm.define "tduprezS" do |tduprezS|
        tduprezS.vm.box = "bento/debian-13"
        tduprezS.vm.box_version = "202508.10.0"
        tduprezS.vm.network "private_network", ip: "192.168.56.110"
        tduprezS.vm.hostname = "tduprezS"
        tduprezS.vm.provision "shell", path: "./scripts/master_node_install.sh"
        tduprezS.vm.synced_folder "./config", "/home/vagrant/config"
        
        tduprezS.vm.provider "virtualbox" do |v|
            v.cpus = 2
            v.memory = 2048
        end
    end

end