# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # lciulloS 192.168.56.110
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "lciulloS" do |server_vm|
    server_vm.vm.box = "bento/debian-13"
    server_vm.vm.hostname = "lciulloS"
    server_vm.vm.network "private_network", ip: "192.168.56.110"
    server_vm.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024" # pour 512 MB de RAM (ou "1024" pour 1 GB)
      vb.cpus = 1       # allouer 1 CPU
    end
    # Installation de k3s 
    server_vm.vm.provision "shell", path: "install-k3s-master.sh"
    #  Déploiement des manifests
    server_vm.vm.provision "shell", path: "deploy-manifests.sh"
  end

end 