Vagrant.configure("2") do |config|
  # lciulloS 192.168.56.110
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "lciulloS" do |server_vm|
    server_vm.vm.box = "bento/debian-13"
    server_vm.vm.hostname = "lciulloS"
    server_vm.vm.network "private_network", ip: "192.168.56.110"
    server_vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    server_vm.vm.provision "shell", path: "install-k3s-master.sh"
  end

  # lciulloSW 192.168.56.111
  config.vm.define "lciulloSW" do |server_worker_vm|
    server_worker_vm.vm.box = "bento/debian-13"
    server_worker_vm.vm.hostname = "lciulloSW"
    server_worker_vm.vm.network "private_network", ip: "192.168.56.111"
    server_worker_vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1 
    end
    server_worker_vm.vm.provision "shell", path: "install-k3s-worker.sh"
  end 
end
