Vagrant.configure("2") do |config|

    config.vm.define "tduprezS" do |tduprezS|
        tduprezS.vm.box = "bento/debian-13"
        tduprezS.vm.box_version = "202508.10.0"
        tduprezS.vm.network "private_network", ip: "192.168.56.110"
        tduprezS.vm.hostname = "tduprezS"
        tduprezS.vm.provision "shell", path: "./scripts/master_node_install.sh"
        
        tduprezS.vm.provider "virtualbox" do |v|
            v.cpus = 2
            v.memory = 2048
        end
    end
    
    config.vm.define "tduprezSW" do |tduprezSW|
        tduprezSW.vm.box = "bento/debian-13"
        tduprezSW.vm.box_version = "202508.10.0"
        tduprezSW.vm.network "private_network", ip: "192.168.56.111"
        tduprezSW.vm.hostname = "tduprezSW"
        tduprezSW.vm.provision "shell", path: "./scripts/worker_node_install.sh"

        tduprezSW.vm.provider "virtualbox" do |v|
            v.cpus = 1
            v.memory = 512
        end
    end

end